/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./../components/AppIcon.vue')['default']
    AppProviders: typeof import('./../components/AppProviders.vue')['default']
    ApprovalActions: typeof import('./../components/ApprovalActions.vue')['default']
    BizDocPreview: typeof import('./../components/BizDocPreview.vue')['default']
    FlowCanvas: typeof import('./../components/FlowCanvas.vue')['default']
    FlowTimeline: typeof import('./../components/FlowTimeline.vue')['default']
    FlowTrack: typeof import('./../components/FlowTrack.vue')['default']
    IconLucideBell: typeof import('~icons/lucide/bell')['default']
    IconLucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    IconLucideEllipsis: typeof import('~icons/lucide/ellipsis')['default']
    IconLucideFileText: typeof import('~icons/lucide/file-text')['default']
    IconLucideGitPullRequestArrow: typeof import('~icons/lucide/git-pull-request-arrow')['default']
    IconLucideHexagon: typeof import('~icons/lucide/hexagon')['default']
    IconLucideLock: typeof import('~icons/lucide/lock')['default']
    IconLucideMoon: typeof import('~icons/lucide/moon')['default']
    IconLucidePanelLeft: typeof import('~icons/lucide/panel-left')['default']
    IconLucidePanelLeftClose: typeof import('~icons/lucide/panel-left-close')['default']
    IconLucidePenSquare: typeof import('~icons/lucide/pen-square')['default']
    IconLucideRefreshCcw: typeof import('~icons/lucide/refresh-ccw')['default']
    IconLucideShield: typeof import('~icons/lucide/shield')['default']
    IconLucideShieldCheck: typeof import('~icons/lucide/shield-check')['default']
    IconLucideSun: typeof import('~icons/lucide/sun')['default']
    IconLucideUserRound: typeof import('~icons/lucide/user-round')['default']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NSelect: typeof import('naive-ui')['NSelect']
    NTag: typeof import('naive-ui')['NTag']
    RichTextEditor: typeof import('./../components/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
